openapi: 3.0.1
info:
  title: PISP Demo Server Open API
  description: This is part of the PISP demo server that handles communication with 
    the mobile app. Note - The API supports a maximum size of 65536 bytes (64 Kilobytes) 
    in the HTTP header.
  license:
    name: Apache 2.0
  version: "1.1"
servers:
  - url: /
paths:
  /health:
     $ref: '../../../node_modules/@mojaloop/api-snippets/thirdparty/openapi3/paths/health.yaml'
